apiVersion: apps/v1
kind: Deployment
metadata:
  name: eauction-app
spec:
  selector:
    matchLabels:
      app: eauction-app
  replicas: 1
  template:
    metadata:
      labels:
        app: eauction-app
    spec:
      containers:
        - name: eauction-app
          image: nadirpayam/eauctionapp:latest

          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi